
### GET all blog posts
GET http://localhost:3003/api/blogs

### GET not existing url error
GET http://localhost:3003/api/blo


### (Create) POST a new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Second Blog Post",
  "author": "Johnie",
  "url": "http://example.com/Second-blog-post",
  "likes": 0
}

### (create) POST another blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Reposted Blog Post",
  "author": "John Oldie",
  "url": "http://example.com/old-blog-post",
  "likes": 5
}

### Try to (create) POST with missing information
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "John Oldie",
  "url": "http://example.com/old-blog-post",
  "likes": 5
}

### GET all blog posts after creating new ones
GET http://localhost:3003/api/blogs

### GET a specific blog post by ID
GET http://localhost:3003/api/blogs/686872a6afa837e8fbc8080f

### delete a blog post by ID
DELETE http://localhost:3003/api/blogs/686872a6afa837e8fbc8080f
