
### GET all blog posts
GET http://localhost:3003/api/blogs

### GET not existing url error
GET http://localhost:3003/api/blo


### (Create) POST a new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Second Blog Post",
  "author": "Johnie",
  "url": "http://example.com/Second-blog-post",
  "likes": 0
}

### (create) POST another blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Reposted Blog Post",
  "author": "John Oldie",
  "url": "http://example.com/old-blog-post",
  "likes": 5
}

### Try to (create) POST with missing information
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "John Oldie",
  "url": "http://example.com/old-blog-post",
  "likes": 5
}

### GET all blog posts after creating new ones
GET http://localhost:3003/api/blogs

### GET a specific blog post by ID
GET http://localhost:3003/api/blogs/686872a6afa837e8fbc8080f

### delete a blog post by ID
DELETE http://localhost:3003/api/blogs/686872a6afa837e8fbc8080f


### update a blog post by ID
PUT http://localhost:3003/api/blogs/6868776f0e037cddcfc3c737
Content-Type: application/json

{
  "title": "Reposted BlogGGG Post",
  "author": "John OldieEEEEE",
  "url": "http://example.com/old-blog-postTT",
  "likes": 500
}

###################################################################
### (Create) POST a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Second User",
  "username": "johnie",
  "password": "password123"
}
### (Create) POST a nother user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Just another User",
  "username": "Mads",
  "password": "1112221"
}

### GET all blog users
GET http://localhost:3003/api/users

###################################################################

### Try login and get token back
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "johnie",
  "password": "password123"
}
// {
//   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5pZSIsImlkIjoiNjg3MDBjZmJlNTg5ZjEzZmQ3YWY1ZTRlIiwiaWF0IjoxNzUyMjQ2NjE3fQ.xFb1rprT3CcVeVIJ7hzm8llQKoXs609mazfu6Uy6rfI",
//   "username": "johnie",
//   "name": "Second User"
// }

### Try login and get token back
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Mads",
  "password": "1112221"
}

### (Create) POST a new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hZHMiLCJpZCI6IjY4NzEyYTE3NGRjZmY4OTVjOTRjMzM2OSIsImlhdCI6MTc1MjI0ODUyOH0.-T1Dikmoky7zxG_cUxv6xuOhWfU9grcIk0S-7ugX8ow

{
  "title": "Mads Blog Post",
  "author": "Madss",
  "url": "http://example.com/Mads-blog-post",
  "likes": 69
}