# Name of the action defined in the document
name: Super Linter

# Runs on every push and pull_request 
on: [push, pull_request]


jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest # windows and macos also directly available

    steps:
      - name: Checkout Code 
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4
        with:
          fetch-dept: 0

      - name: Lint Code Base
        # https://github.com/marketplace/actions/super-linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
